// react/src/Zoompinch.tsx
import React, { useRef, useEffect, ReactNode, useState, forwardRef, useImperativeHandle } from 'react';
import { Zoompinch as ZoompinchCore, Transform } from '@zoompinch/core';
import './Zoompinch.css';

export interface ZoompinchRef {
  applyTransform: (
    scale: number, 
    wrapperInnerCoords: [number, number], 
    canvasCoords: [number, number], 
    rotate?: number
  ) => void;
  composePoint: (x: number, y: number) => [number, number];
  normalizeClientCoords: (clientX: number, clientY: number) => [number, number];
  rotateCanvas: (x: number, y: number, radians: number) => void;
  zoompinchEngine: ZoompinchCore | null;
  canvasWidth: number;
  canvasHeight: number;
}

export interface ZoompinchProps {
  style?: React.CSSProperties;
  transform?: Transform;
  onTransformChange?: (transform: Transform) => void;
  offset?: {
    top: number;
    right: number;
    bottom: number;
    left: number;
  };
  maxScale?: number;
  minScale?: number;
  clampBounds?: boolean;
  rotation?: boolean;
  mouse?: boolean;
  wheel?: boolean;
  touch?: boolean;
  gesture?: boolean;
  zoomSpeed?: number;
  translateSpeed?: number;
  zoomSpeedAppleTrackpad?: number;
  translateSpeedAppleTrackpad?: number;
  children?: ReactNode;
  matrix?: ReactNode | ((props: { composePoint: (x: number, y: number) => [number, number]; normalizeClientCoords: (clientX: number, clientY: number) => [number, number]; canvasWidth: number; canvasHeight: number }) => ReactNode);
  onInit?: () => void;
  onClick?: (event: React.MouseEvent) => void;
  onMouseDown?: (event: React.MouseEvent) => void;
  onTouchStart?: (event: React.TouchEvent) => void;
  onMouseup?: (event: React.MouseEvent) => void;
  onTouchend?: (event: React.TouchEvent) => void;
}

export const Zoompinch = forwardRef<ZoompinchRef, ZoompinchProps>(({
  transform = { translateX: 0, translateY: 0, scale: 1, rotate: 0 },
  offset = { left: 0, top: 0, right: 0, bottom: 0 },
  minScale = 0.5,
  maxScale = 10,
  clampBounds = false,
  rotation = true,
  mouse = true,
  wheel = true,
  touch = true,
  gesture = true,
  zoomSpeed,
  translateSpeed,
  zoomSpeedAppleTrackpad,
  translateSpeedAppleTrackpad,
  children,
  matrix,
  style,
  onTransformChange,
  onInit,
  onClick,
  onMouseDown,
  onTouchStart,
  onMouseup,
  onTouchend,
}, ref) => {
  const zoompinchRef = useRef<HTMLDivElement>(null);
  const zoompinchEngine = useRef<ZoompinchCore>(null);

  const ready = useRef(false);

  const [matrixData, setMatrixData] = useState({
    composePoint: (x: number, y: number): [number, number] => [0, 0],
    canvasWidth: 0,
    canvasHeight: 0,
  });

  const normalizeClientCoords = useRef<(clientX: number, clientY: number) => [number, number]>((clientX, clientY) => {
    if (zoompinchEngine.current) {
      return zoompinchEngine.current.normalizeClientCoords(clientX, clientY);
    }
    return [0, 0];
  });

  useImperativeHandle(ref, () => ({
      applyTransform: (scale, wrapperInnerCoords, canvasCoords, rotate) => {
        if (!zoompinchEngine.current) return;
        if (rotate !== undefined) {
          zoompinchEngine.current.rotate = rotate;
        }
        zoompinchEngine.current.applyTransform(scale, wrapperInnerCoords, canvasCoords);
      },
      composePoint: (x, y) => {
        if (matrixData.composePoint) {
          return matrixData.composePoint(x, y);
        }
        return [0, 0];
      },
      normalizeClientCoords: (clientX, clientY) => {
        if (normalizeClientCoords.current) {
          return normalizeClientCoords.current(clientX, clientY);
        }
        return [0, 0];
      },
      rotateCanvas: (x, y, radians) => {
        if (!zoompinchEngine.current) return;
        zoompinchEngine.current.rotateCanvas(x, y, radians);
      },
      zoompinchEngine: zoompinchEngine.current,
      canvasWidth: matrixData.canvasWidth,
      canvasHeight: matrixData.canvasHeight,
    }));

  function syncReactiveData() {
    if (!zoompinchEngine.current) return;
    setMatrixData({
      composePoint: zoompinchEngine.current!.composePoint.bind(zoompinchEngine.current),
      canvasWidth: zoompinchEngine.current!.canvasBounds?.width ?? 0,
      canvasHeight: zoompinchEngine.current!.canvasBounds?.height ?? 0,
    });
  }

  useEffect(() => {
    if (!zoompinchRef.current || zoompinchEngine.current) return;

    // Jetzt mit den Props initialisieren
    zoompinchEngine.current = new ZoompinchCore(zoompinchRef.current, offset, transform.translateX, transform.translateY, transform.scale, transform.rotate, minScale, maxScale, clampBounds, rotation);

    if (zoomSpeed !== undefined) {
      zoompinchEngine.current.zoomSpeed = zoomSpeed;
    }
    if (translateSpeed !== undefined) {
      zoompinchEngine.current.translateSpeed = translateSpeed;
    }
    if (zoomSpeedAppleTrackpad !== undefined) {
      zoompinchEngine.current.zoomSpeedAppleTrackpad = zoomSpeedAppleTrackpad;
    }
    if (translateSpeedAppleTrackpad !== undefined) {
      zoompinchEngine.current.translateSpeedAppleTrackpad = translateSpeedAppleTrackpad;
    }

    zoompinchEngine.current.addEventListener('update', () => {
      if (!zoompinchEngine.current) return;
      const newTransform = {
        translateX: zoompinchEngine.current.translateX,
        translateY: zoompinchEngine.current.translateY,
        scale: zoompinchEngine.current.scale,
        rotate: zoompinchEngine.current.rotate,
      };

      if (onTransformChange && (newTransform.translateX !== transform.translateX || newTransform.translateY !== transform.translateY || newTransform.scale !== transform.scale || newTransform.rotate !== transform.rotate)) {
        onTransformChange(newTransform);
      }

      syncReactiveData();
    });
    zoompinchEngine.current.addEventListener('load', () => {
      if (!zoompinchEngine.current) return;
      ready.current = true;
      if (onInit) {
        onInit();
      }
      syncReactiveData();
    });
  }, []);

  // Make the function reactive
  // const composePoint = useRef<(x: number, y: number) => [number, number]>(null);
  // const normalizeClientCoords = useRef<(clientX: number, clientY: number) => [number, number]>((clientX: number, clientY: number) => {
  //   if (zoompinchEngine.current) {
  //     return zoompinchEngine.current.normalizeClientCoords(clientX, clientY);
  //   }
  //   return [0, 0];
  // });
  // const canvasWidth = useRef<number>(0);
  // const canvasHeight = useRef<number>(0);

  useEffect(() => {
    if (!zoompinchEngine.current || !ready.current) return;

    if (zoompinchEngine.current.translateX !== transform.translateX || zoompinchEngine.current.translateY !== transform.translateY || zoompinchEngine.current.scale !== transform.scale || zoompinchEngine.current.rotate !== transform.rotate) {
      zoompinchEngine.current.translateX = transform.translateX;
      zoompinchEngine.current.translateY = transform.translateY;
      zoompinchEngine.current.scale = transform.scale;
      zoompinchEngine.current.rotate = transform.rotate;

      zoompinchEngine.current.update();
    }
  }, [transform]);

  useEffect(() => {
    if (!zoompinchEngine.current || !ready.current) return;

    zoompinchEngine.current.offset = offset;
    zoompinchEngine.current.update();
  }, [offset]);

  useEffect(() => {
    if (!zoompinchEngine.current || !ready.current) return;

    zoompinchEngine.current.minScale = minScale;
    zoompinchEngine.current.update();
  }, [minScale]);

  useEffect(() => {
    if (!zoompinchEngine.current || !ready.current) return;

    zoompinchEngine.current.maxScale = maxScale;
    zoompinchEngine.current.update();
  }, [maxScale]);

  useEffect(() => {
    if (!zoompinchEngine.current || !ready.current) return;

    zoompinchEngine.current.clampBounds = clampBounds;

    zoompinchEngine.current.setTranslateFromUserGesture(zoompinchEngine.current.translateX, zoompinchEngine.current.translateY);
    zoompinchEngine.current.update();
  }, [clampBounds]);

  useEffect(() => {
    if (!zoompinchEngine.current || !ready.current) return;

    zoompinchEngine.current.rotation = rotation;
    zoompinchEngine.current.update();
  }, [rotation]);

  useEffect(() => {
    if (!zoompinchEngine.current || !ready.current) return;

    if (zoomSpeed !== undefined) {
      zoompinchEngine.current.zoomSpeed = zoomSpeed;
    }
  }, [zoomSpeed]);

  useEffect(() => {
    if (!zoompinchEngine.current || !ready.current) return;

    if (translateSpeed !== undefined) {
      zoompinchEngine.current.translateSpeed = translateSpeed;
    }
  }, [translateSpeed]);

  useEffect(() => {
    if (!zoompinchEngine.current || !ready.current) return;

    if (zoomSpeedAppleTrackpad !== undefined) {
      zoompinchEngine.current.zoomSpeedAppleTrackpad = zoomSpeedAppleTrackpad;
    }
  }, [zoomSpeedAppleTrackpad]);

  useEffect(() => {
    if (!zoompinchEngine.current || !ready.current) return;

    if (translateSpeedAppleTrackpad !== undefined) {
      zoompinchEngine.current.translateSpeedAppleTrackpad = translateSpeedAppleTrackpad;
    }
  }, [translateSpeedAppleTrackpad]);

  const handleWheel = (event: WheelEvent) => {
    if (!zoompinchEngine.current || !wheel) return;
    event.preventDefault();
    zoompinchEngine.current.handleWheel(event);
  };

  const handleGesturestart = (event: any) => {
    if (!zoompinchEngine.current || !gesture) return;
    zoompinchEngine.current.handleGesturestart(event);
  };

  const handleGesturechange = (event: any) => {
    if (!zoompinchEngine.current || !gesture) return;
    zoompinchEngine.current.handleGesturechange(event);
  };

  const handleGestureend = (event: any) => {
    if (!zoompinchEngine.current || !gesture) return;
    zoompinchEngine.current.handleGestureend(event);
  };

  const handleMousedown = (event: MouseEvent) => {
    if (!zoompinchEngine.current || !mouse) return;
    zoompinchEngine.current.handleMousedown(event);
  };

  const handleMousemove = (event: MouseEvent) => {
    if (!zoompinchEngine.current || !mouse) return;
    zoompinchEngine.current.handleMousemove(event);
  };

  const handleMouseup = (event: MouseEvent) => {
    if (!zoompinchEngine.current || !mouse) return;
    zoompinchEngine.current.handleMouseup(event);
  };

  const handleTouchstart = (event: TouchEvent) => {
    if (!zoompinchEngine.current || !touch) return;
    zoompinchEngine.current.handleTouchstart(event);
  };

  const handleTouchmove = (event: TouchEvent) => {
    if (!zoompinchEngine.current || !touch) return;
    zoompinchEngine.current.handleTouchmove(event);
  };

  const handleTouchend = (event: TouchEvent) => {
    if (!zoompinchEngine.current || !touch) return;
    zoompinchEngine.current.handleTouchend(event);
  };

  useEffect(() => {
    if (!zoompinchRef.current) return;
    const element = zoompinchRef.current;
    window.addEventListener('gesturechange', handleGesturechange);
    window.addEventListener('gestureend', handleGestureend);
    window.addEventListener('mousemove', handleMousemove);
    window.addEventListener('mouseup', handleMouseup);
    window.addEventListener('touchmove', handleTouchmove);
    window.addEventListener('touchend', handleTouchend);


    element.addEventListener('wheel', handleWheel, { passive: false })
    element.addEventListener('gesturestart', handleGesturestart, { passive: false });
    element.addEventListener('mousedown', handleMousedown, { passive: false });
    element.addEventListener('touchstart', handleTouchstart, { passive: false });

    return () => {
      window.removeEventListener('gesturechange', handleGesturechange);
      window.removeEventListener('gestureend', handleGestureend);
      window.removeEventListener('mousemove', handleMousemove);
      window.removeEventListener('mouseup', handleMouseup);
      window.removeEventListener('touchmove', handleTouchmove);
      window.removeEventListener('touchend', handleTouchend);
      element.removeEventListener('wheel', handleWheel);
      element.removeEventListener('gesturestart', handleGesturestart);
      element.removeEventListener('mousedown', handleMousedown);
      element.removeEventListener('touchstart', handleTouchstart);
    };
  }, [mouse, touch, gesture, wheel]);

  return (
    <div
      ref={zoompinchRef}
      className="zoompinch"
      style={style}
      onClick={onClick}
      onMouseDown={onMouseDown}
      onTouchStart={onTouchStart}
      onMouseUp={onMouseup}
      onTouchEnd={onTouchend}
    >
      <div className="canvas">{children}</div>
      <div className="matrix">
        {typeof matrix === 'function'
          ? matrix({
              composePoint: matrixData.composePoint,
              normalizeClientCoords: normalizeClientCoords.current,
              canvasWidth: matrixData.canvasWidth,
              canvasHeight: matrixData.canvasHeight,
            })
          : matrix}
      </div>
    </div>
  );
});

Zoompinch.displayName = 'Zoompinch';

// vue/src/components/Zoompinch.vue
<template>
  <div ref="zoompinchRef" class="zoompinch" @wheel="handleWheel" @gesturestart="handleGesturestart" @mousedown="handleMousedown" @touchstart="handleTouchstart">
    <div class="canvas">
      <slot name="default" />
    </div>
    <div class="matrix">
      <slot v-if="ready && composePoint" name="matrix" :compose-point="composePoint" :normalize-client-coords="normalizeClientCoords" :canvas-width="canvasWidth" :canvas-height="canvasHeight" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { Transform, Zoompinch } from '@zoompinch/core';
import { ref, toRef, computed, onMounted, watch, toRefs, onUnmounted, reactive, watchEffect, VNode } from 'vue';

const props = withDefaults(
  defineProps<{
    transform?: Transform;
    offset?: {
      top: number;
      right: number;
      bottom: number;
      left: number;
    };
    maxScale?: number;
    minScale?: number;
    clampBounds?: boolean;
    rotation?: boolean;
    mouse?: boolean;
    wheel?: boolean;
    touch?: boolean;
    gesture?: boolean;
    zoomSpeed?: number;
    translateSpeed?: number;
    zoomSpeedAppleTrackpad?: number;
    translateSpeedAppleTrackpad?: number;
  }>(),
  {
    transform: () => ({ translateX: 0, translateY: 0, scale: 1, rotate: 0 }),
    offset: () => ({ left: 0, top: 0, right: 0, bottom: 0 }),
    minScale: 0.5,
    maxScale: 10,
    clampBounds: false,
    rotation: true,
    mouse: true,
    wheel: true,
    touch: true,
    gesture: true,
  }
);
const emit = defineEmits<{
  'update:transform': [transform: Transform];
  'init': [];
  dragGestureStart: [event: MouseEvent | TouchEvent | WheelEvent];
  dragGestureEnd: [event: MouseEvent | TouchEvent | WheelEvent];
}>();

const zoompinchRef = ref<HTMLDivElement>();
const zoompinchEngine = ref<Zoompinch>();

const ready = ref(false);

(window as any).zoompinchEngine = zoompinchEngine;

const composePoint = ref<(x: number, y: number) => [number, number]>(() => {
  throw new Error('Not initialized yet');
});

const canvasWidth = ref(0);
const canvasHeight = ref(0);

onMounted(() => {
  if (!zoompinchRef.value) return;
  zoompinchEngine.value = new Zoompinch(zoompinchRef.value, props.offset, props.transform.translateX, props.transform.translateY, props.transform.scale, props.transform.rotate, props.minScale, props.maxScale, props.clampBounds, props.rotation);

  if (props.zoomSpeed !== undefined) {
    zoompinchEngine.value.zoomSpeed = props.zoomSpeed;
  }
  if (props.translateSpeed !== undefined) {
    zoompinchEngine.value.translateSpeed = props.translateSpeed;
  }
  if (props.zoomSpeedAppleTrackpad !== undefined) {
    zoompinchEngine.value.zoomSpeedAppleTrackpad = props.zoomSpeedAppleTrackpad;
  }
  if (props.translateSpeedAppleTrackpad !== undefined) {
    zoompinchEngine.value.translateSpeedAppleTrackpad = props.translateSpeedAppleTrackpad;
  }

  zoompinchEngine.value.addEventListener('init', () => {
    emit('init');
  });

  zoompinchEngine.value.addEventListener('update', () => {
    if (!zoompinchEngine.value) return;
    const newTransform = {
      translateX: zoompinchEngine.value.translateX,
      translateY: zoompinchEngine.value.translateY,
      scale: zoompinchEngine.value.scale,
      rotate: zoompinchEngine.value.rotate,
    };
    if (newTransform.translateX !== props.transform.translateX || newTransform.translateY !== props.transform.translateY || newTransform.scale !== props.transform.scale || newTransform.rotate !== props.transform.rotate) {
      emit('update:transform', newTransform);
    }

    composePoint.value = (x: number, y: number) => {
      return zoompinchEngine.value!.composePoint(x, y);
    };
    canvasWidth.value = zoompinchEngine.value.canvasBounds.width;
    canvasHeight.value = zoompinchEngine.value.canvasBounds.height;
  });
  zoompinchEngine.value.addEventListener('init', () => {
    ready.value = true;
  });
});

watch(
  () => props.transform,
  () => {
    if (!zoompinchEngine.value) return;
    if (
      zoompinchEngine.value.translateX !== props.transform.translateX ||
      zoompinchEngine.value.translateY !== props.transform.translateY ||
      zoompinchEngine.value.scale !== props.transform.scale ||
      zoompinchEngine.value.rotate !== props.transform.rotate
    ) {
      zoompinchEngine.value.translateX = props.transform.translateX;
      zoompinchEngine.value.translateY = props.transform.translateY;
      zoompinchEngine.value.scale = props.transform.scale;
      zoompinchEngine.value.rotate = props.transform.rotate;

      zoompinchEngine.value.update();
    }
  },
  { deep: true }
);
watch(
  () => props.offset,
  (newOffset) => {
    if (!zoompinchEngine.value) return;
    zoompinchEngine.value.offset = newOffset;
    zoompinchEngine.value.update();
  },
  { deep: true }
);
watch(
  () => props.minScale,
  (newMinScale) => {
    if (!zoompinchEngine.value) return;
    zoompinchEngine.value.minScale = newMinScale;
    zoompinchEngine.value.update();
  }
);
watch(
  () => props.maxScale,
  (newMaxScale) => {
    if (!zoompinchEngine.value) return;
    zoompinchEngine.value.maxScale = newMaxScale;
    zoompinchEngine.value.update();
  }
);
watch(() => props.clampBounds, (newClampBounds) => {
  if (!zoompinchEngine.value) return;
  zoompinchEngine.value.clampBounds = newClampBounds;
  // The clamp is an explicit user intention
  // The reason is that we do not want side effects when toggling the clamp
  zoompinchEngine.value.setTranslateFromUserGesture(zoompinchEngine.value.translateX, zoompinchEngine.value.translateY);
  zoompinchEngine.value.update();
});
watch(() => props.rotation, (newRotation) => {
  if (!zoompinchEngine.value) return;
  zoompinchEngine.value.rotation = newRotation;
  zoompinchEngine.value.update();
});

watch(() => props.zoomSpeed, () => {
  if (!zoompinchEngine.value || props.zoomSpeed === undefined) return;
  zoompinchEngine.value.zoomSpeed = props.zoomSpeed;
});
watch(() => props.translateSpeed, () => {
  if (!zoompinchEngine.value || props.translateSpeed === undefined) return;
  zoompinchEngine.value.translateSpeed = props.translateSpeed;
});
watch(() => props.zoomSpeedAppleTrackpad, () => {
  if (!zoompinchEngine.value || props.zoomSpeedAppleTrackpad === undefined) return;
  zoompinchEngine.value.zoomSpeedAppleTrackpad = props.zoomSpeedAppleTrackpad;
});
watch(() => props.translateSpeedAppleTrackpad, () => {
  if (!zoompinchEngine.value || props.translateSpeedAppleTrackpad === undefined) return;
  zoompinchEngine.value.translateSpeedAppleTrackpad = props.translateSpeedAppleTrackpad;
});

const applyTransform = (scale: number, wrapperInnerCoords: [number, number], canvasCoords: [number, number], rotate?: number) => {
  if (!zoompinchEngine.value) return;
  if (rotate !== undefined) {
    zoompinchEngine.value.rotate = rotate;
  }
  zoompinchEngine.value.applyTransform(scale, wrapperInnerCoords, canvasCoords);
};

const handleWheel = (event: WheelEvent) => {
  if (!zoompinchEngine.value) return;
  if (props.wheel) {
    zoompinchEngine.value.handleWheel(event);
  }
};
const handleGesturestart = (event: any) => {
  if (!zoompinchEngine.value) return;
  if (props.gesture) {
    zoompinchEngine.value.handleGesturestart(event);
  }
};
const handleGesturechange = (event: any) => {
  if (!zoompinchEngine.value) return;
  if (props.gesture) {
    zoompinchEngine.value.handleGesturechange(event);
  }
};
const handleGestureend = (event: any) => {
  if (!zoompinchEngine.value) return;
  if (props.gesture) {
    zoompinchEngine.value.handleGestureend(event);
  }
};
const handleMousedown = (event: MouseEvent) => {
  if (!zoompinchEngine.value) return;
  if (props.mouse) {
    zoompinchEngine.value.handleMousedown(event);
  }
};
const handleMousemove = (event: MouseEvent) => {
  if (!zoompinchEngine.value) return;
  if (props.mouse) {
    zoompinchEngine.value.handleMousemove(event);
  }
};
const handleMouseup = (event: MouseEvent) => {
  if (!zoompinchEngine.value) return;
  if (props.mouse) {
    zoompinchEngine.value.handleMouseup(event);
  }
};
const handleTouchstart = (event: TouchEvent) => {
  if (!zoompinchEngine.value) return;
  if (props.touch) {
    zoompinchEngine.value.handleTouchstart(event);
  }
};
const handleTouchmove = (event: TouchEvent) => {
  if (!zoompinchEngine.value) return;
  if (props.touch) {
    zoompinchEngine.value.handleTouchmove(event);
  }
};
const handleTouchend = (event: TouchEvent) => {
  if (!zoompinchEngine.value) return;
  if (props.touch) {
    zoompinchEngine.value.handleTouchend(event);
  }
};

window.addEventListener('gesturechange', handleGesturechange);
window.addEventListener('gestureend', handleGestureend);
window.addEventListener('mousemove', handleMousemove);
window.addEventListener('mouseup', handleMouseup);
window.addEventListener('touchmove', handleTouchmove);
window.addEventListener('touchend', handleTouchend);
onUnmounted(() => {
  window.removeEventListener('gesturechange', handleGesturechange);
  window.removeEventListener('gestureend', handleGestureend);
  window.removeEventListener('mousemove', handleMousemove);
  window.removeEventListener('mouseup', handleMouseup);
  window.removeEventListener('touchmove', handleTouchmove);
  window.removeEventListener('touchend', handleTouchend);
});

const normalizeClientCoords = (clientX: number, clientY: number) => {
  if (!zoompinchEngine.value) {
    throw new Error('Zoompinch engine not initialized');
  }
  return zoompinchEngine.value.normalizeClientCoords(clientX, clientY);
};

const rotateCanvas = (x: number, y: number, radians: number) => {
  if (!zoompinchEngine.value) return;
  zoompinchEngine.value.rotateCanvas(x, y, radians);
};

const slots = defineSlots<{
  default: () => VNode | VNode[];
  matrix: (args: { composePoint: (x: number, y: number) => [number, number]; normalizeClientCoords: (clientX: number, clientY: number) => [number, number]; canvasWidth: number; canvasHeight: number }) => VNode | VNode[];
}>();

defineExpose({
  applyTransform,
  composePoint,
  normalizeClientCoords,
  zoompinchEngine,
  canvasWidth,
  canvasHeight,
  rotateCanvas
});
</script>

<style scoped lang="css">
.zoompinch {
  touch-action: none;
  overflow: hidden;
  width: 100%;
  height: 100%;
  position: relative;
}
.zoompinch > .canvas {
  position: absolute;
}
.zoompinch > .matrix {
  pointer-events: none;
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  left: 0;
}
</style>
