// playground/src/components/Playground.vue
<template>
  <div class="playground">
    <header>
      <section>
        <div class="title">Offset</div>
        <div class="fields-wrapper">
          <div class="field">
            <div class="description">Offset Top</div>
            <div class="value">
              <n-input-number v-model:value="offset.top" />
            </div>
          </div>
          <div class="field">
            <div class="description">Offset Right</div>
            <div class="value">
              <n-input-number v-model:value="offset.right" />
            </div>
          </div>
          <div class="field">
            <div class="description">Offset Bottom</div>
            <div class="value">
              <n-input-number v-model:value="offset.bottom" />
            </div>
          </div>
          <div class="field">
            <div class="description">Offset Left</div>
            <div class="value">
              <n-input-number v-model:value="offset.left" />
            </div>
          </div>
        </div>
      </section>
      <section>
        <div class="title">Transform</div>
        <div class="fields-wrapper">
          <div class="field">
            <div class="description">Translate X</div>
            <div class="value">
              <n-input-number v-model:value="transform.translateX" />
            </div>
          </div>
          <div class="field">
            <div class="description">Translate Y</div>
            <div class="value">
              <n-input-number v-model:value="transform.translateY" />
            </div>
          </div>
          <div class="field">
            <div class="description">Scale</div>
            <div class="value">
              <n-input-number v-model:value="transform.scale" />
            </div>
          </div>
          <div class="field">
            <div class="description">Rotate</div>
            <div class="value">
              <n-input-number v-model:value="transform.rotate" />
            </div>
          </div>
        </div>
      </section>
      <section>
        <div class="title">Events</div>
        <div class="fields-wrapper small">
          <div class="field">
            <div class="description">Wheel</div>
            <div class="value">
              <n-switch v-model:value="wheelEvents" />
            </div>
          </div>
          <div class="field">
            <div class="description">Touch</div>
            <div class="value">
              <n-switch v-model:value="touchEvents" />
            </div>
          </div>
          <div class="field">
            <div class="description">Mouse</div>
            <div class="value">
              <n-switch v-model:value="mouseEvents" />
            </div>
          </div>
          <div class="field">
            <div class="description">Gesture</div>
            <div class="value">
              <n-switch v-model:value="gestureEvents" />
            </div>
          </div>
          <div class="field">
            <div class="description">Rotation</div>
            <div class="value">
              <n-switch v-model:value="rotation" />
            </div>
          </div>
          <div class="field">
            <div class="description">Bounds</div>
            <div class="value">
              <n-switch v-model:value="clampBounds" />
            </div>
          </div>
        </div>
      </section>
      <section>
        <n-button @click="fit()" type="success" style="width: 100%"> Fit </n-button>
      </section>
    </header>
    <div class="projection-wrapper">
      <zoompinch ref="zoompinchRef" :offset="offset" v-model:transform="transform" :min-scale="0.35" :max-scale="10" :rotation="rotation" :clamp-bounds="clampBounds" :mouse="mouseEvents" :touch="touchEvents" :wheel="wheelEvents" :gesture="gestureEvents">
        <img src="https://imagedelivery.net/mudX-CmAqIANL8bxoNCToA/489df5b2-38ce-46e7-32e0-d50170e8d800/public"></img>
        <template #matrix="{ composePoint }">
          <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" style="pointer-events: all" @click="handleClickOnLayer">
            <circle :cx="composePoint(1536 / 2, 2048 / 2)[0]" :cy="composePoint(1536 / 2, 2048 / 2)[1]" r="5" style="fill: #f00"></circle>
          </svg>
        </template>
      </zoompinch>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Zoompinch } from '@zoompinch/vue';
import '@zoompinch/vue/style.css';
import { onMounted, reactive, ref, watch, watchEffect } from 'vue';
import { NInputNumber, NSwitch, NButton } from 'naive-ui';

// Flicker bug reproducable: 100,0,0.1,180

const rotation = ref(true);
const clampBounds = ref(false);
watch(clampBounds, (newValue) => {
  if (newValue) {
    rotation.value = false;
  }
});
watch(rotation, (newValue) => {
  if (newValue) {
    clampBounds.value = false;
  }
});
const zoompinchRef = ref<InstanceType<typeof Zoompinch>>();

const offset = reactive({ top: 10, right: 10, bottom: 10, left: 10 });
(window as any).offset = offset;

const transform = ref({ translateX: 0, translateY: 0, scale: 1, rotate: 0 });

(window as any).zoompinchRef = zoompinchRef;

const mouseEvents = ref(true);
const touchEvents = ref(true);
const wheelEvents = ref(true);
const gestureEvents = ref(true);

function handleClickOnLayer(event: MouseEvent) {
  if (!zoompinchRef.value) return;
  const [x, y] = zoompinchRef.value.normalizeClientCoords(event.clientX, event.clientY);
  alert(`Clicked on layer at normalized coords: ${x.toFixed(2)}, ${y.toFixed(2)}`);
}
function fit() {
  if (!zoompinchRef.value) return;
  // transform.value = { translateX: 0, translateY: 0, scale: 1, radians: 0 };
  console.log('FITTING!!!');
  zoompinchRef.value.applyTransform(1, [0.5, 0.5], [0.5, 0.5], 0);
}
// onMounted(() => {
//   setTimeout(() => fit(true));
// });

// watch(
//   () => zoompinchRef.value?.wrapperBounds,
//   () => {
//     requestAnimationFrame(() => {
//       zoompinchRef.value?.applyTransform(1, [0.5, 0.5], [0.5, 0.5], false);
//     });
//   }
// );
</script>

<style scoped lang="scss">
.playground {
  width: 100%;
  height: 100%;
  box-sizing: border-box;
  padding: 10px;
  display: flex;
  overflow: hidden;
  flex-direction: row;

  gap: 10px;
  @media screen and (max-width: 700px) {
    flex-direction: column;
  }
  > header {
    border-radius: 10px;
    padding: 20px;
    display: grid;
    flex: none;
    box-sizing: border-box;
    gap: 20px;
    place-content: start stretch;
    //place-content: space-between;
    background-color: #f1f1f1;
    @media screen and (min-width: 701px) {
      width: 400px;
    }
    .title {
      display: none;
    }
    > section + section {
      border-top: 1px solid rgba(0, 0, 0, 0.1);
      padding-top: 10px;
    }
  }
  > .projection-wrapper {
    flex: 1;
  }
  .fields-wrapper {
    width: 100%;
    display: grid;
    gap: 10px;

    grid-template-columns: repeat(auto-fill, minmax(120px, 1fr));
    @media screen and (max-width: 700px) {
      grid-template-columns: repeat(4, 1fr);
    }

    &.small {
      grid-template-columns: repeat(auto-fill, minmax(50px, 1fr));
      @media screen and (max-width: 700px) {
        grid-template-columns: repeat(auto-fill, minmax(40px, 1fr));
      }
    }
    .field {
      .description {
        font-size: 0.9em;
        opacity: 0.7;
        @media screen and (max-width: 700px) {
          font-size: 0.7em;
        }
      }
      .n-input-number {
        ::v-deep(.n-input__suffix) {
          .n-button {
            @media screen and (max-width: 700px) {
              display: none;
            }
          }
        }
      }
    }
  }
  .zoompinch {
    border-radius: 10px;
    background-color: #f1f1f1;
    @media screen and (max-width: 700px) {
      width: 100%;
      height: 100%;
    }
  }
}
</style>

// react/playground/main.tsx
import React, { useRef, useState } from 'react';
import ReactDOM from 'react-dom/client';
import { Zoompinch } from '../src/index';
import { ZoompinchRef } from '../src/Zoompinch';
import { Transform } from '@zoompinch/core';

function App() {
  const zoompinchRef = useRef<ZoompinchRef>(null);
  const [transform, setTransform] = useState({
    translateX: 0,
    translateY: 0,
    scale: 1,
    rotate: 0
  });

  function handleInit() {
    // Center canvas on initialization
    zoompinchRef.current?.applyTransform(1, [0.5, 0.5], [0.5, 0.5], 0);
  }

  function handleTransformChange(newTransform: Transform) {
    console.log('Transform updated:', newTransform);
  }

  function handleClick(event: React.MouseEvent) {
    if (!zoompinchRef.current) return;
    const [x, y] = zoompinchRef.current.normalizeClientCoords(event.clientX, event.clientY);
    console.log('Clicked at canvas position:', x, y);
  }

  return (
    <Zoompinch
      ref={zoompinchRef}
      style={{ width: '800px', height: '600px', border: '1px solid #ccc' }}
      transform={transform}
      onTransformChange={handleTransformChange}
      offset={{ top: 0, right: 0, bottom: 0, left: 0 }}
      minScale={0.5}
      maxScale={4}
      clampBounds={false}
      rotation={true}
      mouse={true}
      wheel={true}
      touch={true}
      gesture={true}
      onInit={handleInit}
      onClick={handleClick}
      matrix={({ composePoint, normalizeClientCoords, canvasWidth, canvasHeight }) => {
        const [x, y] = composePoint(100, 100);

        return (
          <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%">
            <circle cx={x} cy={y} r="5" fill="#f00" />
          </svg>
        );
      }}
    >
      <img 
        width="1536" 
        height="2048" 
        src="https://imagedelivery.net/mudX-CmAqIANL8bxoNCToA/489df5b2-38ce-46e7-32e0-d50170e8d800/public"
        draggable={false}
        style={{ userSelect: 'none' }}
      />
    </Zoompinch>
  );
}

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
